apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        image: pgvector/pgvector:pg18
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: holochatstats-config
        - secretRef:
            name: holochatstats-secrets
        env:
        - name: PGDATA
          value: /var/lib/postgresql/18/docker
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/18/docker
      volumes:
      - name: pgdata
        emptyDir: {}
