import { useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import { AlertTriangle, Info, Loader2, Search } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Tooltip, TooltipContent, TooltipProvider, TooltipTrigger,
} from "@/components/ui/tooltip"
import { VideoModal } from "@/components/video/VideoModal"
import { DemoNotice } from "@/components/DemoNotice"
import { api } from "@/lib/api"
import { registerEriContext } from "@/components/eri/eri-context"
interface SearchResult {
  video_id: string
  topic: string
  summary: string
  video_title: string
  date: string
  youtube_url: string
}
export default function HighlightSearch() {
  const { t } = useTranslation()
  const [query, setQuery] = useState("")
  const [results, setResults] = useState<SearchResult[] | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [modal, setModal] = useState<{ videoId: string; start: number } | null>(null)
  useEffect(() => {
    registerEriContext(() => ({
      page: "highlight_search",
      endpoint: "/api/search_highlights",
      parameters: { query },
      description: `Viewing AI highlight search results for query: "${query}"`,
    }))
    return () => registerEriContext(null)
  }, [query])
  const performSearch = async () => {
    if (!query.trim()) {
      setError(t("Please enter a search query."))
      return
    }
    setError(null)
    setLoading(true)
    setResults(null)
    try {
      const res = await api.get("/search_highlights", { params: { query } })
      if (!res.data.success || !res.data.data || res.data.data.length === 0) {
        setError(t("No results found."))
        return
      }
      setResults(res.data.data)
    } catch {
      setError(t("Error fetching data. Please try again later."))
    } finally {
      setLoading(false)
    }
  }
  const openResult = (r: SearchResult) => {
    const params = new URLSearchParams(r.youtube_url.split("?")[1])
    const raw = params.get("t")
    setModal({ videoId: r.video_id, start: raw ? parseInt(raw.replace("s", ""), 10) : 0 })
  }
  return (
    <TooltipProvider>
      <div className="flex flex-col gap-4">
        <h2 className="text-2xl font-bold text-center flex items-center justify-center gap-2">
          {t("AI Highlight Search")}
          <Tooltip>
            <TooltipTrigger asChild>
              <Info className="h-4 w-4 text-muted-foreground cursor-help" />
            </TooltipTrigger>
            <TooltipContent className="max-w-sm">
              {t("Search for moments using semantic meaning. You can use operators like channel:<name>, from:<YYYY-MM-DD>, and to:<YYYY-MM-DD>.")}
            </TooltipContent>
          </Tooltip>
        </h2>
        <DemoNotice />
        <div className="flex items-center gap-2 rounded-md border border-yellow-600/40 bg-yellow-950/40 text-yellow-200 text-sm p-2 justify-center text-center">
          <AlertTriangle className="h-4 w-4 flex-shrink-0" />
          <span>
            <strong>{t("Disclaimer:")}</strong>{" "}
            {t("Summaries are generated by an AI and may contain errors or misinterpretations. Always watch the linked timestamp for the full context.")}
          </span>
        </div>
        <div className="flex gap-2 max-w-2xl mx-auto w-full">
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && performSearch()}
            placeholder={t("e.g., paper boat channel:saba from:2025-08-01")}
          />
          <Button onClick={performSearch} disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
            <span className="ml-2">{t("Search")}</span>
          </Button>
        </div>
        {error && <p className="text-center text-destructive text-sm">{error}</p>}
        <div className="rounded-lg bg-card min-h-[300px] max-h-[65vh] overflow-y-auto">
          {loading && (
            <div className="flex justify-center py-10">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          )}
          {!loading && !results && !error && (
            <p className="text-center text-muted-foreground p-10">{t("Search for highlights to see results.")}</p>
          )}
          {!loading && results && (
            <div className="flex flex-col">
              {results.map((r, i) => (
                <div
                  key={i}
                  className="flex items-start gap-4 p-4 border-b border-border last:border-b-0 cursor-pointer hover:bg-white/5 transition-colors"
                  onClick={() => openResult(r)}
                >
                  <img
                    src={`https://img.youtube.com/vi/${r.video_id}/mqdefault.jpg`}
                    alt={r.video_title}
                    className="w-[160px] h-[90px] object-cover rounded-md flex-shrink-0"
                  />
                  <div>
                    <div className="font-bold text-primary">{r.topic}</div>
                    <div className="text-sm text-muted-foreground mt-1">{r.summary}</div>
                    <div className="text-xs text-muted-foreground/70 mt-2">{r.video_title} ({r.date})</div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      <VideoModal
        open={!!modal}
        onOpenChange={(open) => !open && setModal(null)}
        videoId={modal?.videoId ?? null}
        startSeconds={modal?.start ?? null}
      />
    </TooltipProvider>
  )
}