import { useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import { AlertTriangle, Info, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select"
import { MonthPicker } from "@/components/ui/month-picker"
import {
  Tooltip, TooltipContent, TooltipProvider, TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger,
} from "@/components/ui/accordion"
import { VideoModal } from "@/components/video/VideoModal"
import { DemoNotice } from "@/components/DemoNotice"
import { api } from "@/lib/api"
import { registerEriContext } from "@/components/eri/eri-context"
interface TimestampItem {
  topic: string
  summary: string
  youtube_url: string
}
interface VideoHighlight {
  video_id: string
  video_title: string
  timestamps: TimestampItem[]
}
export default function Highlights() {
  const { t, i18n } = useTranslation()
  const [channels, setChannels] = useState<string[]>([])
  const [channel, setChannel] = useState("")
  const [month, setMonth] = useState("")
  const [videos, setVideos] = useState<VideoHighlight[] | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [modal, setModal] = useState<{ videoId: string; start: number } | null>(null)
  useEffect(() => {
    api.get("/get_channel_names").then((res) => setChannels(res.data || []))
  }, [])
  useEffect(() => {
    registerEriContext(() => ({
      page: "highlights",
      endpoint: "/api/get_video_highlights",
      parameters: { month, channel_name: channel },
      description: `Viewing AI video highlights for ${channel} in ${month}`,
    }))
    return () => registerEriContext(null)
  }, [channel, month])
  const fetchData = async () => {
    if (!channel || !month) {
      setError(t("Please select a channel and a month."))
      return
    }
    setError(null)
    setLoading(true)
    setVideos(null)
    try {
      const res = await api.get("/get_video_highlights", { params: { channel_name: channel, month } })
      if (!res.data.success || !res.data.data || res.data.data.length === 0) {
        setError(t("No highlights available for this selection."))
        return
      }
      setVideos(res.data.data)
    } catch {
      setError(t("Error fetching data. Please try again later."))
    } finally {
      setLoading(false)
    }
  }
  const openTimestamp = (ts: TimestampItem, videoId: string) => {
    const match = ts.youtube_url.match(/&t=(\d+)s/)
    setModal({ videoId, start: match ? parseInt(match[1], 10) : 0 })
  }
  return (
    <TooltipProvider>
      <div className="flex flex-col gap-4">
        <h2 className="text-2xl font-bold text-center flex items-center justify-center gap-2">
          {t("AI Video Highlights")}
          <Tooltip>
            <TooltipTrigger asChild>
              <Info className="h-4 w-4 text-muted-foreground cursor-help" />
            </TooltipTrigger>
            <TooltipContent className="max-w-sm">
              {t("AI-generated summaries of the most interesting moments in a stream, determined by analyzing chat reactions.")}
            </TooltipContent>
          </Tooltip>
        </h2>
        <DemoNotice />
        <div className="flex items-center gap-2 rounded-md border border-yellow-600/40 bg-yellow-950/40 text-yellow-200 text-sm p-2 justify-center text-center">
          <AlertTriangle className="h-4 w-4 flex-shrink-0" />
          <span>
            <strong>{t("Disclaimer:")}</strong>{" "}
            {t("Summaries are generated by an AI and may contain errors or misinterpretations. Always watch the linked timestamp for the full context.")}
          </span>
        </div>
        <div className="flex flex-wrap items-end justify-center gap-4">
          <div className="space-y-1.5">
            <Label>{t("Channel:")}</Label>
            <Select value={channel} onValueChange={setChannel}>
              <SelectTrigger className="w-[220px]">
                <SelectValue placeholder={t("Select Channel")} />
              </SelectTrigger>
              <SelectContent>
                {channels.map((c) => (
                  <SelectItem key={c} value={c}>{c}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>{t("Month:")}</Label>
            <MonthPicker value={month} onChange={setMonth} locale={i18n.language} className="w-[200px]" />
          </div>
          <Button onClick={fetchData} disabled={loading}>
            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            {t("Fetch Highlights")}
          </Button>
        </div>
        {error && <p className="text-center text-destructive text-sm">{error}</p>}
        <div className="rounded-lg bg-card p-4 min-h-[300px] max-h-[65vh] overflow-y-auto">
          {loading && (
            <div className="flex justify-center py-10">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          )}
          {!loading && videos && (
            <Accordion type="multiple">
              {videos.map((v, i) => (
                <AccordionItem key={v.video_id + i} value={`item-${i}`}>
                  <AccordionTrigger>
                    <div className="flex items-center gap-3 text-left">
                      <img
                        src={`https://img.youtube.com/vi/${v.video_id}/mqdefault.jpg`}
                        alt={v.video_title}
                        className="w-[120px] h-[90px] object-cover rounded-md flex-shrink-0"
                      />
                      <span>{v.video_title}</span>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="flex flex-col">
                      {v.timestamps.map((ts, j) => (
                        <div
                          key={j}
                          className="cursor-pointer p-3 border-b border-border last:border-b-0 hover:bg-white/5 transition-colors"
                          onClick={() => openTimestamp(ts, v.video_id)}
                        >
                          <div className="font-bold text-primary">{ts.topic}</div>
                          <div className="text-sm text-muted-foreground">{ts.summary}</div>
                        </div>
                      ))}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          )}
        </div>
      </div>
      <VideoModal
        open={!!modal}
        onOpenChange={(open) => !open && setModal(null)}
        videoId={modal?.videoId ?? null}
        startSeconds={modal?.start ?? null}
      />
    </TooltipProvider>
  )
}